{{- /*
templates/configmap.yaml
Creates a ConfigMap to hold the custom LDIF files from the correct values path.
*/}}
{{- if and .Values.directory.customLdifs (not .Values.directory.quickstart.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-ldifs
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  {{- range $filename, $content := .Values.directory.customLdifs }}
  {{ $filename }}: |-
    {{ $content | nindent 4 }}
  {{- end }}
{{- end }}
