{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openldap-ha.fullname" . }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "openldap-ha.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "openldap-ha.selectorLabels" . | nindent 6 }}
{{- end }}