{{- /*
templates/secret.yaml
Renders the secret for OpenLDAP credentials.
It creates a secret only if auth.existingSecret is not set.
*/}}
{{- if (include "openldap-enterprise.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap-enterprise.secretName" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
  # Manage admin-password: use provided value or generate a random one.
  admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "openldap-enterprise.secretName" .) "key" "admin-password" "providedValues" (list "auth.adminPassword") "length" 16 "context" $) }}
  # Manage config-password: use provided value or generate a random one.
  config-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "openldap-enterprise.secretName" .) "key" "config-password" "providedValues" (list "auth.configPassword") "length" 16 "context" $) }}
{{- end }}